### ISSUE TITLE
add map function to tree data structure

### ISSUE THREAD

**Issue by brucou** [joaonuno/tree-model-js#30]
Given a tree, return a tree of the same structure made up of the objects returned by the callback which is executed at each node. Similar to `Array.map` or `_,map` (underscore library).

Example : `node.map(function (node, parent_node, index, root_node) {/*SOMETHING*/}) :: tree`

From the `walk` method, it should be relatively straightforwardly derived. It is still good I think to have in the API.

**Comment by joaonuno** [comment]
Thank you for the suggestion. I'm closing this issue for now because I have other priorities for this library besides making it more functional (as in functional programming). Maybe this library is more suited to your needs http://aaronstacy.com/t-js/ as it already implements the traversal methods you are requesting. While I might consider this in the future, I don't currently have use cases for these kind of tree transformation functions.

**Comment by brucou** [comment]
Long time has passed, I did my own functional library as we discussed at some point : https://github.com/brucou/functional-rose-tree

**Comment by joaonuno** [comment]
Great work, congrats! Seems solid.

**Comment by brucou** [comment]
Thanks!!
